"""added nullable true to author link

Revision ID: 32087f53ea9e
Revises: fa55cba7cd9c
Create Date: 2023-02-06 14:03:21.440067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32087f53ea9e'
down_revision = 'fa55cba7cd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
