"""alter chat_id on chat to string

Revision ID: 91620b7ac567
Revises: d660c8b1dafa
Create Date: 2023-02-03 18:04:16.456967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91620b7ac567'
down_revision = 'd660c8b1dafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'chat_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
