"""added code column to messenger

Revision ID: af9337be5436
Revises: 32087f53ea9e
Create Date: 2023-02-12 15:24:19.140834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9337be5436'
down_revision = '32087f53ea9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messenger', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messenger', 'code')
    # ### end Alembic commands ###
