"""alter array field

Revision ID: c71d6c153520
Revises: 0019191656ec
Create Date: 2023-02-04 19:44:22.253157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71d6c153520'
down_revision = '0019191656ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
