"""added default value to last message id field

Revision ID: cda1458710d5
Revises: 48c4eaebce9e
Create Date: 2023-02-02 16:41:25.449462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda1458710d5'
down_revision = '48c4eaebce9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
