"""fix grammatic mistake

Revision ID: d660c8b1dafa
Revises: cda1458710d5
Create Date: 2023-02-02 16:46:51.862520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd660c8b1dafa'
down_revision = 'cda1458710d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author_phone', sa.String(), nullable=True))
    op.drop_column('message', 'auhtor_phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('auhtor_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('message', 'author_phone')
    # ### end Alembic commands ###
