"""added author link field

Revision ID: fa55cba7cd9c
Revises: 22850cecb1e2
Create Date: 2023-02-06 13:59:25.701446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa55cba7cd9c'
down_revision = '22850cecb1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'author_link')
    # ### end Alembic commands ###
